server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/monopoly?createDatabaseIfNotExist=true
    username: luke
    password: DtAhixzPfLbVv7kEBodL
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
